apiVersion: v2
name: grafana
description: Grafana component for Karavel
type: application
version: 1.0.0
appVersion: 8.4.4
maintainers:
  - name: MatteoJoliveau
    email: matteo.joliveau@mikamai.com

home: https://grafana.com
sources:
  - https://github.com/integr8ly/grafana-operator
  - https://github.com/karavel-io/platform

annotations:
  karavel.io/dependencies: cert-manager, external-secrets
  dex.enable: dex
  nginx.enable: ingress-nginx
