apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "grafana.name" . }}-operated-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}-operated-tls
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ (urlParse (required "parameter 'publicURL' is required for generating Grafana certificate" .Values.publicURL)).host }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretname: {{ include "grafana.name" . }}-operated-tls
