{{- if .Values.secret.key }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "grafana.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}-secrets
  {{- include "grafana.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.secret.store.name }}
    kind: {{ .Values.secret.store.kind }}
  target:
    creationPolicy: 'Owner'
  dataFrom:
    - key: {{ .Values.secret.key }}
{{- end }}
