{{- with .Values.secret }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "grafana.name" $ }}-secrets
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" $ }}-secrets
  {{- include "grafana.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .store.name }}
    kind: {{ .store.kind }}
  target:
    creationPolicy: 'Owner'
  dataFrom:
    - key: {{ required (printf "parameter 'secret.key' is required for generating %s-secrets" (include "grafana.name" .)) .key }}
{{- end }}
