apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: {{ include "grafana.name" . }}-operated
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}-operated
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  deployment:
    replicas: 1
    labels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}-operated
      {{- include "grafana.labels" . | nindent 6 }}
    skipCreateAdminAccount: false
    envFrom:
      {{ if .Values.secret.key }}
      - secretRef:
          name: {{ include "grafana.name" . }}-secrets
      {{- end }}
      {{- if .Values.dex.enable }}
      - secretRef:
          name: dex-{{ include "grafana.name" . }}-credentials
      - configMapRef:
          name: {{ include "grafana.name" . }}-dex-config
      {{- end }}
    terminationGracePeriodSeconds: 60
  service:
    labels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}-operated
      {{- include "grafana.labels" . | nindent 6 }}
  ingress:
    enabled: true
    {{- $url := urlParse (required "parameter 'publicURL' is required for generating Grafana instance" .Values.publicURL) }}
    hostname: {{ $url.host }}
    path: /
    pathType: Prefix
    tlsEnabled: true
    tlsSecretName: {{ include "grafana.name" . }}-operated-tls
    labels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}-operated
      {{- include "grafana.labels" . | nindent 6 }}
  client:
    preferService: true
    timeout: 10000
  jsonnet:
    libraryLabelSelector:
      matchLabels:
        grafana.integreatly.org/instance: {{ include "grafana.name" . }}-operated
  config:
    server:
      root_url: {{ .Values.publicURL }}
    log:
      mode: console
      level: warn
    auth:
      disable_login_form: true
      disable_signout_menu: false
    auth.anonymous:
      enabled: false
    auth.generic_oauth:
      enabled: true
    users:
      viewers_can_edit: true
  dashboardLabelSelector:
    - matchExpressions:
        - {key: grafana.integreatly.org/instance, operator: In, values: [{{ include "grafana.name" . }}-operated]}
