apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana-operator
    {{- include "grafana.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-operator
  labels:
    app.kubernetes.io/name: grafana-operator
    {{- include "grafana.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadashboards
      - grafanadashboards/status
    verbs: ['get', 'list', 'update', 'watch']
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
    verbs: ['get', 'list', 'watch']
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - serviceaccounts
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - watch
      - create
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - watch
  - apiGroups:
      - integreatly.org
    resources:
      - grafanas
      - grafanas/status
      - grafanas/finalizers
      - grafanadashboards
      - grafanadatasources
      - grafanadatasources/status
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - deletecollection
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-operator
  labels:
    app.kubernetes.io/name: grafana-operator
    {{- include "grafana.labels" . | nindent 4 }}
roleRef:
  name: grafana-operator
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: {{ .Release.Namespace }}

