apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.name" . }}-operator-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}-operator
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "grafana.name" . }}-operator
    {{- include "grafana.selectorLabels" . | nindent 4 }}
