apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.name" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}-operator
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}-operator
    {{- include "grafana.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grafana.name" . }}-operator
        {{- include "grafana.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "grafana.name" . }}-operator
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        command:
        - /manager
        args:
        - --zap-log-level=info
        - --scan-all
        - --grafana-image={{ .Values.grafana.image }}
        - --grafana-image-tag={{ .Values.grafana.tag | default .Chart.AppVersion }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.operator.image }}:{{ .Values.operator.tag }}"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
